# DOCS:
# > Realiza acciones administrativas del entorno de la aplicación.
# >
# > Cabe destacar que se encarga de generar la documentación y el autocompletado
# :DOCS

# RECIPE:Instalar aplicación desde repositorio:
# 1. Modifica el fichero ```app/custom/config/custom.yml``` (Si no existe copia desde custom.example.yml)
# 2. Establece la configuración de la aplicación en la propiedad *apps*. Estableciendo el nombre de la aplicación y la url del repositorio.
#    ```yml
#    apps:
#      dm: https://github.com/diglesiahoz/way.code.app.dm.git
#    ```
# 3. Guarda el fichero ```app/custom/config/custom.yml```
# 4. Ejecuta ```way core.init -v```
# :RECIPE

# RECIPE:Cambiar el address pool por defecto de Docker:
# 1. Establece fichero /etc/docker/daemon.json
# ```
# echo '{
#   "default-address-pools": [
#     {
#       "base": "172.80.0.0/16",
#       "size": 24
#     }
#   ]
# }' | sudo tee /etc/docker/daemon.json > /dev/null
# ```
# 2. Re-inicia servicio docker
# ```
# sudo systemctl restart docker
# ```
# :RECIPE

help: "Ejecuta tareas administrativas"
example:
- (({}.tmp.proc.sig))

task:
  do:
    -
      call: init

            
