help: "Obtiene información de ficheros de configuración"
example:
- (({}.tmp.proc.sig))
- (({}.tmp.proc.sig)) @*.local


# Propiedad que establece el uso del procedimiento de forma interna. No permitido uso mediante CLI.
allowed: false

task:
  require:
    config: 
      - conf
  do:
    - 
      check:
        data:
          -
            key: (({conf}._scope))
            is: decoded
        true:
          -
            call: getConfigFromCLI
            args:
              config: (({conf}._scope))
        false:
          -
            call: getConfigFromCLI
            args:
              config: (({conf}))

