# DOCS:description:
# Realiza acciones administrativas del entorno de la aplicación.
# :DOCS

# DOCS:tip::
# Se encarga de generar la documentación y el autocompletado
# :DOCS

# DOCS:example:
# way core.init -v
# :DOCS

task:
  do:
    -
      call: init

            
