FROM node:20-alpine

# Crear directorio de trabajo
WORKDIR /docs

# Copiar entrypoint (usa ruta dentro del contexto)
COPY entrypoint/docker-entrypoint.docs.sh /docker-entrypoint.docs.sh

# Cambiar permisos como root
RUN chmod +x /docker-entrypoint.docs.sh

# Usar entrypoint
ENTRYPOINT ["/docker-entrypoint.docs.sh"]
